import os

# NocoDB Configuration
NOCODB_BASE_URL = os.getenv('NOCODB_BASE_URL', 'http://localhost:8080')
NOCODB_TOKEN = os.getenv('NOCODB_TOKEN', '')
NOCODB_PROJECT_ID = os.getenv('NOCODB_PROJECT_ID', '')

# Table IDs
NOCODB_HISTORY_FILTERS_TABLE_ID = os.getenv('NOCODB_HISTORY_FILTERS_TABLE_ID', '')
NOCODB_HISTORY_FILTERS_VIEW_ID = os.getenv('NOCODB_HISTORY_FILTERS_VIEW_ID', '')
NOCODB_INTERACTED_USERS_TABLE_ID = os.getenv('NOCODB_INTERACTED_USERS_TABLE_ID', '')
NOCODB_INTERACTED_USERS_VIEW_ID = os.getenv('NOCODB_INTERACTED_USERS_VIEW_ID', '')
